/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU8Decoder,
  getU8Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type Codec,
  type Decoder,
  type EncodedAccount,
  type Encoder,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const CHAT_CONTEXT_DISCRIMINATOR = new Uint8Array([
  28, 122, 31, 214, 78, 136, 26, 215,
]);

export function getChatContextDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CHAT_CONTEXT_DISCRIMINATOR,
  );
}

export type ChatContext = {
  discriminator: ReadonlyUint8Array;
  text: string;
  seed: number;
  bump: number;
};

export type ChatContextArgs = { text: string; seed: number; bump: number };

/** Gets the encoder for {@link ChatContextArgs} account data. */
export function getChatContextEncoder(): Encoder<ChatContextArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["text", addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
      ["seed", getU8Encoder()],
      ["bump", getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: CHAT_CONTEXT_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link ChatContext} account data. */
export function getChatContextDecoder(): Decoder<ChatContext> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["text", addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    ["seed", getU8Decoder()],
    ["bump", getU8Decoder()],
  ]);
}

/** Gets the codec for {@link ChatContext} account data. */
export function getChatContextCodec(): Codec<ChatContextArgs, ChatContext> {
  return combineCodec(getChatContextEncoder(), getChatContextDecoder());
}

export function decodeChatContext<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<ChatContext, TAddress>;
export function decodeChatContext<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<ChatContext, TAddress>;
export function decodeChatContext<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<ChatContext, TAddress> | MaybeAccount<ChatContext, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getChatContextDecoder(),
  );
}

export async function fetchChatContext<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<ChatContext, TAddress>> {
  const maybeAccount = await fetchMaybeChatContext(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeChatContext<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<ChatContext, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeChatContext(maybeAccount);
}

export async function fetchAllChatContext(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<ChatContext>[]> {
  const maybeAccounts = await fetchAllMaybeChatContext(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeChatContext(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<ChatContext>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeChatContext(maybeAccount));
}
