/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const CRED_SCORE_DISCRIMINATOR = new Uint8Array([
  155, 131, 21, 207, 245, 116, 2, 244,
]);

export function getCredScoreDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(CRED_SCORE_DISCRIMINATOR);
}

export type CredScore = { discriminator: ReadonlyUint8Array; score: number };

export type CredScoreArgs = { score: number };

/** Gets the encoder for {@link CredScoreArgs} account data. */
export function getCredScoreEncoder(): FixedSizeEncoder<CredScoreArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["score", getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: CRED_SCORE_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link CredScore} account data. */
export function getCredScoreDecoder(): FixedSizeDecoder<CredScore> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["score", getU8Decoder()],
  ]);
}

/** Gets the codec for {@link CredScore} account data. */
export function getCredScoreCodec(): FixedSizeCodec<CredScoreArgs, CredScore> {
  return combineCodec(getCredScoreEncoder(), getCredScoreDecoder());
}

export function decodeCredScore<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<CredScore, TAddress>;
export function decodeCredScore<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<CredScore, TAddress>;
export function decodeCredScore<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<CredScore, TAddress> | MaybeAccount<CredScore, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getCredScoreDecoder(),
  );
}

export async function fetchCredScore<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<CredScore, TAddress>> {
  const maybeAccount = await fetchMaybeCredScore(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeCredScore<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<CredScore, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeCredScore(maybeAccount);
}

export async function fetchAllCredScore(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<CredScore>[]> {
  const maybeAccounts = await fetchAllMaybeCredScore(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeCredScore(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<CredScore>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeCredScore(maybeAccount));
}

export function getCredScoreSize(): number {
  return 9;
}
