/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  type Address,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  type ParsedCallbackFromLlmInstruction,
  type ParsedChatWithLlmInstruction,
  type ParsedInitializeInstruction,
} from "../instructions";

export const DEFI_SCORE_AGENT_EXAMPLE_PROGRAM_ADDRESS =
  "3PXKKoDvK8TUF7mmszeXozkaZS7KGbtUEg3dn3r8PTkL" as Address<"3PXKKoDvK8TUF7mmszeXozkaZS7KGbtUEg3dn3r8PTkL">;

export enum DefiScoreAgentExampleAccount {
  Agent,
  ChatContext,
  Config,
  CredScore,
}

export function identifyDefiScoreAgentExampleAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): DefiScoreAgentExampleAccount {
  const data = "data" in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([47, 166, 112, 147, 155, 197, 86, 7]),
      ),
      0,
    )
  ) {
    return DefiScoreAgentExampleAccount.Agent;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([28, 122, 31, 214, 78, 136, 26, 215]),
      ),
      0,
    )
  ) {
    return DefiScoreAgentExampleAccount.ChatContext;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([155, 12, 170, 224, 30, 250, 204, 130]),
      ),
      0,
    )
  ) {
    return DefiScoreAgentExampleAccount.Config;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([155, 131, 21, 207, 245, 116, 2, 244]),
      ),
      0,
    )
  ) {
    return DefiScoreAgentExampleAccount.CredScore;
  }
  throw new Error(
    "The provided account could not be identified as a defiScoreAgentExample account.",
  );
}

export enum DefiScoreAgentExampleInstruction {
  CallbackFromLlm,
  ChatWithLlm,
  Initialize,
}

export function identifyDefiScoreAgentExampleInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): DefiScoreAgentExampleInstruction {
  const data = "data" in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([64, 202, 209, 39, 156, 18, 216, 170]),
      ),
      0,
    )
  ) {
    return DefiScoreAgentExampleInstruction.CallbackFromLlm;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([208, 23, 234, 221, 106, 104, 249, 150]),
      ),
      0,
    )
  ) {
    return DefiScoreAgentExampleInstruction.ChatWithLlm;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([175, 175, 109, 31, 13, 152, 155, 237]),
      ),
      0,
    )
  ) {
    return DefiScoreAgentExampleInstruction.Initialize;
  }
  throw new Error(
    "The provided instruction could not be identified as a defiScoreAgentExample instruction.",
  );
}

export type ParsedDefiScoreAgentExampleInstruction<
  TProgram extends string = "3PXKKoDvK8TUF7mmszeXozkaZS7KGbtUEg3dn3r8PTkL",
> =
  | ({
      instructionType: DefiScoreAgentExampleInstruction.CallbackFromLlm;
    } & ParsedCallbackFromLlmInstruction<TProgram>)
  | ({
      instructionType: DefiScoreAgentExampleInstruction.ChatWithLlm;
    } & ParsedChatWithLlmInstruction<TProgram>)
  | ({
      instructionType: DefiScoreAgentExampleInstruction.Initialize;
    } & ParsedInitializeInstruction<TProgram>);
