/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  transformEncoder,
  type AccountMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type WritableAccount,
} from "@solana/kit";
import { DEFI_SCORE_AGENT_EXAMPLE_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";

export const CALLBACK_FROM_LLM_DISCRIMINATOR = new Uint8Array([
  64, 202, 209, 39, 156, 18, 216, 170,
]);

export function getCallbackFromLlmDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CALLBACK_FROM_LLM_DISCRIMINATOR,
  );
}

export type CallbackFromLlmInstruction<
  TProgram extends string = typeof DEFI_SCORE_AGENT_EXAMPLE_PROGRAM_ADDRESS,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountUser extends string | AccountMeta<string> = string,
  TAccountCredScore extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountUser extends string
        ? ReadonlyAccount<TAccountUser>
        : TAccountUser,
      TAccountCredScore extends string
        ? WritableAccount<TAccountCredScore>
        : TAccountCredScore,
      ...TRemainingAccounts,
    ]
  >;

export type CallbackFromLlmInstructionData = {
  discriminator: ReadonlyUint8Array;
  response: string;
};

export type CallbackFromLlmInstructionDataArgs = { response: string };

export function getCallbackFromLlmInstructionDataEncoder(): Encoder<CallbackFromLlmInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["response", addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
    ]),
    (value) => ({ ...value, discriminator: CALLBACK_FROM_LLM_DISCRIMINATOR }),
  );
}

export function getCallbackFromLlmInstructionDataDecoder(): Decoder<CallbackFromLlmInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["response", addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
  ]);
}

export function getCallbackFromLlmInstructionDataCodec(): Codec<
  CallbackFromLlmInstructionDataArgs,
  CallbackFromLlmInstructionData
> {
  return combineCodec(
    getCallbackFromLlmInstructionDataEncoder(),
    getCallbackFromLlmInstructionDataDecoder(),
  );
}

export type CallbackFromLlmAsyncInput<
  TAccountConfig extends string = string,
  TAccountUser extends string = string,
  TAccountCredScore extends string = string,
> = {
  config: Address<TAccountConfig>;
  user: Address<TAccountUser>;
  credScore?: Address<TAccountCredScore>;
  response: CallbackFromLlmInstructionDataArgs["response"];
};

export async function getCallbackFromLlmInstructionAsync<
  TAccountConfig extends string,
  TAccountUser extends string,
  TAccountCredScore extends string,
  TProgramAddress extends Address =
    typeof DEFI_SCORE_AGENT_EXAMPLE_PROGRAM_ADDRESS,
>(
  input: CallbackFromLlmAsyncInput<
    TAccountConfig,
    TAccountUser,
    TAccountCredScore
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  CallbackFromLlmInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountUser,
    TAccountCredScore
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? DEFI_SCORE_AGENT_EXAMPLE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    config: { value: input.config ?? null, isWritable: false },
    user: { value: input.user ?? null, isWritable: false },
    credScore: { value: input.credScore ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.credScore.value) {
    accounts.credScore.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([99, 114, 101, 100])),
        getAddressEncoder().encode(expectAddress(accounts.user.value)),
      ],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.credScore),
    ],
    data: getCallbackFromLlmInstructionDataEncoder().encode(
      args as CallbackFromLlmInstructionDataArgs,
    ),
    programAddress,
  } as CallbackFromLlmInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountUser,
    TAccountCredScore
  >);
}

export type CallbackFromLlmInput<
  TAccountConfig extends string = string,
  TAccountUser extends string = string,
  TAccountCredScore extends string = string,
> = {
  config: Address<TAccountConfig>;
  user: Address<TAccountUser>;
  credScore: Address<TAccountCredScore>;
  response: CallbackFromLlmInstructionDataArgs["response"];
};

export function getCallbackFromLlmInstruction<
  TAccountConfig extends string,
  TAccountUser extends string,
  TAccountCredScore extends string,
  TProgramAddress extends Address =
    typeof DEFI_SCORE_AGENT_EXAMPLE_PROGRAM_ADDRESS,
>(
  input: CallbackFromLlmInput<TAccountConfig, TAccountUser, TAccountCredScore>,
  config?: { programAddress?: TProgramAddress },
): CallbackFromLlmInstruction<
  TProgramAddress,
  TAccountConfig,
  TAccountUser,
  TAccountCredScore
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? DEFI_SCORE_AGENT_EXAMPLE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    config: { value: input.config ?? null, isWritable: false },
    user: { value: input.user ?? null, isWritable: false },
    credScore: { value: input.credScore ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.credScore),
    ],
    data: getCallbackFromLlmInstructionDataEncoder().encode(
      args as CallbackFromLlmInstructionDataArgs,
    ),
    programAddress,
  } as CallbackFromLlmInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountUser,
    TAccountCredScore
  >);
}

export type ParsedCallbackFromLlmInstruction<
  TProgram extends string = typeof DEFI_SCORE_AGENT_EXAMPLE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    config: TAccountMetas[0];
    user: TAccountMetas[1];
    credScore: TAccountMetas[2];
  };
  data: CallbackFromLlmInstructionData;
};

export function parseCallbackFromLlmInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedCallbackFromLlmInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      config: getNextAccount(),
      user: getNextAccount(),
      credScore: getNextAccount(),
    },
    data: getCallbackFromLlmInstructionDataDecoder().decode(instruction.data),
  };
}
