/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { DEFI_SCORE_AGENT_EXAMPLE_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";

export const CHAT_WITH_LLM_DISCRIMINATOR = new Uint8Array([
  208, 23, 234, 221, 106, 104, 249, 150,
]);

export function getChatWithLlmDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CHAT_WITH_LLM_DISCRIMINATOR,
  );
}

export type ChatWithLlmInstruction<
  TProgram extends string = typeof DEFI_SCORE_AGENT_EXAMPLE_PROGRAM_ADDRESS,
  TAccountUser extends string | AccountMeta<string> = string,
  TAccountCredScore extends string | AccountMeta<string> = string,
  TAccountInference extends string | AccountMeta<string> = string,
  TAccountAgent extends string | AccountMeta<string> = string,
  TAccountChatContext extends string | AccountMeta<string> = string,
  TAccountOracleProgram extends string | AccountMeta<string> =
    "LLM4VF4uxgbcrUdwF9rBh7MUEypURp8FurEdZLhZqed",
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountUser extends string
        ? WritableSignerAccount<TAccountUser> & AccountSignerMeta<TAccountUser>
        : TAccountUser,
      TAccountCredScore extends string
        ? WritableAccount<TAccountCredScore>
        : TAccountCredScore,
      TAccountInference extends string
        ? WritableAccount<TAccountInference>
        : TAccountInference,
      TAccountAgent extends string
        ? ReadonlyAccount<TAccountAgent>
        : TAccountAgent,
      TAccountChatContext extends string
        ? ReadonlyAccount<TAccountChatContext>
        : TAccountChatContext,
      TAccountOracleProgram extends string
        ? ReadonlyAccount<TAccountOracleProgram>
        : TAccountOracleProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type ChatWithLlmInstructionData = {
  discriminator: ReadonlyUint8Array;
  text: string;
};

export type ChatWithLlmInstructionDataArgs = { text: string };

export function getChatWithLlmInstructionDataEncoder(): Encoder<ChatWithLlmInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["text", addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
    ]),
    (value) => ({ ...value, discriminator: CHAT_WITH_LLM_DISCRIMINATOR }),
  );
}

export function getChatWithLlmInstructionDataDecoder(): Decoder<ChatWithLlmInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["text", addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
  ]);
}

export function getChatWithLlmInstructionDataCodec(): Codec<
  ChatWithLlmInstructionDataArgs,
  ChatWithLlmInstructionData
> {
  return combineCodec(
    getChatWithLlmInstructionDataEncoder(),
    getChatWithLlmInstructionDataDecoder(),
  );
}

export type ChatWithLlmAsyncInput<
  TAccountUser extends string = string,
  TAccountCredScore extends string = string,
  TAccountInference extends string = string,
  TAccountAgent extends string = string,
  TAccountChatContext extends string = string,
  TAccountOracleProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  user: TransactionSigner<TAccountUser>;
  credScore?: Address<TAccountCredScore>;
  inference: Address<TAccountInference>;
  agent?: Address<TAccountAgent>;
  chatContext: Address<TAccountChatContext>;
  oracleProgram?: Address<TAccountOracleProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  text: ChatWithLlmInstructionDataArgs["text"];
};

export async function getChatWithLlmInstructionAsync<
  TAccountUser extends string,
  TAccountCredScore extends string,
  TAccountInference extends string,
  TAccountAgent extends string,
  TAccountChatContext extends string,
  TAccountOracleProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address =
    typeof DEFI_SCORE_AGENT_EXAMPLE_PROGRAM_ADDRESS,
>(
  input: ChatWithLlmAsyncInput<
    TAccountUser,
    TAccountCredScore,
    TAccountInference,
    TAccountAgent,
    TAccountChatContext,
    TAccountOracleProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  ChatWithLlmInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountCredScore,
    TAccountInference,
    TAccountAgent,
    TAccountChatContext,
    TAccountOracleProgram,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? DEFI_SCORE_AGENT_EXAMPLE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    user: { value: input.user ?? null, isWritable: true },
    credScore: { value: input.credScore ?? null, isWritable: true },
    inference: { value: input.inference ?? null, isWritable: true },
    agent: { value: input.agent ?? null, isWritable: false },
    chatContext: { value: input.chatContext ?? null, isWritable: false },
    oracleProgram: { value: input.oracleProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.credScore.value) {
    accounts.credScore.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([99, 114, 101, 100])),
        getAddressEncoder().encode(expectAddress(accounts.user.value)),
      ],
    });
  }
  if (!accounts.agent.value) {
    accounts.agent.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([97, 103, 101, 110, 116])),
      ],
    });
  }
  if (!accounts.oracleProgram.value) {
    accounts.oracleProgram.value =
      "LLM4VF4uxgbcrUdwF9rBh7MUEypURp8FurEdZLhZqed" as Address<"LLM4VF4uxgbcrUdwF9rBh7MUEypURp8FurEdZLhZqed">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.credScore),
      getAccountMeta(accounts.inference),
      getAccountMeta(accounts.agent),
      getAccountMeta(accounts.chatContext),
      getAccountMeta(accounts.oracleProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getChatWithLlmInstructionDataEncoder().encode(
      args as ChatWithLlmInstructionDataArgs,
    ),
    programAddress,
  } as ChatWithLlmInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountCredScore,
    TAccountInference,
    TAccountAgent,
    TAccountChatContext,
    TAccountOracleProgram,
    TAccountSystemProgram
  >);
}

export type ChatWithLlmInput<
  TAccountUser extends string = string,
  TAccountCredScore extends string = string,
  TAccountInference extends string = string,
  TAccountAgent extends string = string,
  TAccountChatContext extends string = string,
  TAccountOracleProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  user: TransactionSigner<TAccountUser>;
  credScore: Address<TAccountCredScore>;
  inference: Address<TAccountInference>;
  agent: Address<TAccountAgent>;
  chatContext: Address<TAccountChatContext>;
  oracleProgram?: Address<TAccountOracleProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  text: ChatWithLlmInstructionDataArgs["text"];
};

export function getChatWithLlmInstruction<
  TAccountUser extends string,
  TAccountCredScore extends string,
  TAccountInference extends string,
  TAccountAgent extends string,
  TAccountChatContext extends string,
  TAccountOracleProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address =
    typeof DEFI_SCORE_AGENT_EXAMPLE_PROGRAM_ADDRESS,
>(
  input: ChatWithLlmInput<
    TAccountUser,
    TAccountCredScore,
    TAccountInference,
    TAccountAgent,
    TAccountChatContext,
    TAccountOracleProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): ChatWithLlmInstruction<
  TProgramAddress,
  TAccountUser,
  TAccountCredScore,
  TAccountInference,
  TAccountAgent,
  TAccountChatContext,
  TAccountOracleProgram,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? DEFI_SCORE_AGENT_EXAMPLE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    user: { value: input.user ?? null, isWritable: true },
    credScore: { value: input.credScore ?? null, isWritable: true },
    inference: { value: input.inference ?? null, isWritable: true },
    agent: { value: input.agent ?? null, isWritable: false },
    chatContext: { value: input.chatContext ?? null, isWritable: false },
    oracleProgram: { value: input.oracleProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.oracleProgram.value) {
    accounts.oracleProgram.value =
      "LLM4VF4uxgbcrUdwF9rBh7MUEypURp8FurEdZLhZqed" as Address<"LLM4VF4uxgbcrUdwF9rBh7MUEypURp8FurEdZLhZqed">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.credScore),
      getAccountMeta(accounts.inference),
      getAccountMeta(accounts.agent),
      getAccountMeta(accounts.chatContext),
      getAccountMeta(accounts.oracleProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getChatWithLlmInstructionDataEncoder().encode(
      args as ChatWithLlmInstructionDataArgs,
    ),
    programAddress,
  } as ChatWithLlmInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountCredScore,
    TAccountInference,
    TAccountAgent,
    TAccountChatContext,
    TAccountOracleProgram,
    TAccountSystemProgram
  >);
}

export type ParsedChatWithLlmInstruction<
  TProgram extends string = typeof DEFI_SCORE_AGENT_EXAMPLE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    user: TAccountMetas[0];
    credScore: TAccountMetas[1];
    inference: TAccountMetas[2];
    agent: TAccountMetas[3];
    chatContext: TAccountMetas[4];
    oracleProgram: TAccountMetas[5];
    systemProgram: TAccountMetas[6];
  };
  data: ChatWithLlmInstructionData;
};

export function parseChatWithLlmInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedChatWithLlmInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      user: getNextAccount(),
      credScore: getNextAccount(),
      inference: getNextAccount(),
      agent: getNextAccount(),
      chatContext: getNextAccount(),
      oracleProgram: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getChatWithLlmInstructionDataDecoder().decode(instruction.data),
  };
}
