/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { DEFI_SCORE_AGENT_EXAMPLE_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const INITIALIZE_DISCRIMINATOR = new Uint8Array([
  175, 175, 109, 31, 13, 152, 155, 237,
]);

export function getInitializeDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(INITIALIZE_DISCRIMINATOR);
}

export type InitializeInstruction<
  TProgram extends string = typeof DEFI_SCORE_AGENT_EXAMPLE_PROGRAM_ADDRESS,
  TAccountSigner extends string | AccountMeta<string> = string,
  TAccountAgent extends string | AccountMeta<string> = string,
  TAccountChatContext extends string | AccountMeta<string> = string,
  TAccountOracleProgram extends string | AccountMeta<string> =
    "LLM4VF4uxgbcrUdwF9rBh7MUEypURp8FurEdZLhZqed",
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSigner extends string
        ? WritableSignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      TAccountAgent extends string
        ? WritableAccount<TAccountAgent>
        : TAccountAgent,
      TAccountChatContext extends string
        ? WritableAccount<TAccountChatContext>
        : TAccountChatContext,
      TAccountOracleProgram extends string
        ? ReadonlyAccount<TAccountOracleProgram>
        : TAccountOracleProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type InitializeInstructionData = {
  discriminator: ReadonlyUint8Array;
  seed: number;
};

export type InitializeInstructionDataArgs = { seed: number };

export function getInitializeInstructionDataEncoder(): FixedSizeEncoder<InitializeInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["seed", getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: INITIALIZE_DISCRIMINATOR }),
  );
}

export function getInitializeInstructionDataDecoder(): FixedSizeDecoder<InitializeInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["seed", getU8Decoder()],
  ]);
}

export function getInitializeInstructionDataCodec(): FixedSizeCodec<
  InitializeInstructionDataArgs,
  InitializeInstructionData
> {
  return combineCodec(
    getInitializeInstructionDataEncoder(),
    getInitializeInstructionDataDecoder(),
  );
}

export type InitializeAsyncInput<
  TAccountSigner extends string = string,
  TAccountAgent extends string = string,
  TAccountChatContext extends string = string,
  TAccountOracleProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  signer: TransactionSigner<TAccountSigner>;
  agent?: Address<TAccountAgent>;
  chatContext: Address<TAccountChatContext>;
  oracleProgram?: Address<TAccountOracleProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  seed: InitializeInstructionDataArgs["seed"];
};

export async function getInitializeInstructionAsync<
  TAccountSigner extends string,
  TAccountAgent extends string,
  TAccountChatContext extends string,
  TAccountOracleProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address =
    typeof DEFI_SCORE_AGENT_EXAMPLE_PROGRAM_ADDRESS,
>(
  input: InitializeAsyncInput<
    TAccountSigner,
    TAccountAgent,
    TAccountChatContext,
    TAccountOracleProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  InitializeInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountAgent,
    TAccountChatContext,
    TAccountOracleProgram,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? DEFI_SCORE_AGENT_EXAMPLE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    agent: { value: input.agent ?? null, isWritable: true },
    chatContext: { value: input.chatContext ?? null, isWritable: true },
    oracleProgram: { value: input.oracleProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.agent.value) {
    accounts.agent.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([97, 103, 101, 110, 116])),
      ],
    });
  }
  if (!accounts.oracleProgram.value) {
    accounts.oracleProgram.value =
      "LLM4VF4uxgbcrUdwF9rBh7MUEypURp8FurEdZLhZqed" as Address<"LLM4VF4uxgbcrUdwF9rBh7MUEypURp8FurEdZLhZqed">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.signer),
      getAccountMeta(accounts.agent),
      getAccountMeta(accounts.chatContext),
      getAccountMeta(accounts.oracleProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getInitializeInstructionDataEncoder().encode(
      args as InitializeInstructionDataArgs,
    ),
    programAddress,
  } as InitializeInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountAgent,
    TAccountChatContext,
    TAccountOracleProgram,
    TAccountSystemProgram
  >);
}

export type InitializeInput<
  TAccountSigner extends string = string,
  TAccountAgent extends string = string,
  TAccountChatContext extends string = string,
  TAccountOracleProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  signer: TransactionSigner<TAccountSigner>;
  agent: Address<TAccountAgent>;
  chatContext: Address<TAccountChatContext>;
  oracleProgram?: Address<TAccountOracleProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  seed: InitializeInstructionDataArgs["seed"];
};

export function getInitializeInstruction<
  TAccountSigner extends string,
  TAccountAgent extends string,
  TAccountChatContext extends string,
  TAccountOracleProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address =
    typeof DEFI_SCORE_AGENT_EXAMPLE_PROGRAM_ADDRESS,
>(
  input: InitializeInput<
    TAccountSigner,
    TAccountAgent,
    TAccountChatContext,
    TAccountOracleProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): InitializeInstruction<
  TProgramAddress,
  TAccountSigner,
  TAccountAgent,
  TAccountChatContext,
  TAccountOracleProgram,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? DEFI_SCORE_AGENT_EXAMPLE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    agent: { value: input.agent ?? null, isWritable: true },
    chatContext: { value: input.chatContext ?? null, isWritable: true },
    oracleProgram: { value: input.oracleProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.oracleProgram.value) {
    accounts.oracleProgram.value =
      "LLM4VF4uxgbcrUdwF9rBh7MUEypURp8FurEdZLhZqed" as Address<"LLM4VF4uxgbcrUdwF9rBh7MUEypURp8FurEdZLhZqed">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.signer),
      getAccountMeta(accounts.agent),
      getAccountMeta(accounts.chatContext),
      getAccountMeta(accounts.oracleProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getInitializeInstructionDataEncoder().encode(
      args as InitializeInstructionDataArgs,
    ),
    programAddress,
  } as InitializeInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountAgent,
    TAccountChatContext,
    TAccountOracleProgram,
    TAccountSystemProgram
  >);
}

export type ParsedInitializeInstruction<
  TProgram extends string = typeof DEFI_SCORE_AGENT_EXAMPLE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    signer: TAccountMetas[0];
    agent: TAccountMetas[1];
    chatContext: TAccountMetas[2];
    oracleProgram: TAccountMetas[3];
    systemProgram: TAccountMetas[4];
  };
  data: InitializeInstructionData;
};

export function parseInitializeInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedInitializeInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      signer: getNextAccount(),
      agent: getNextAccount(),
      chatContext: getNextAccount(),
      oracleProgram: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getInitializeInstructionDataDecoder().decode(instruction.data),
  };
}
